version: '3'
services: 
    reactapp:
        image: reactsample
        ports: 
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - .:/app
        stdin_open: true